# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f482244be36568d0feadd8b8dd320f00"
name = "Retorn-App"
application_url = "https://retorn-app.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://retorn-app.vercel.app/auth/callback",
  "https://retorn-app.vercel.app/auth/shopify/callback"
]
